node{
   stage('SCM Checkout'){
      git 'https://github.com/dharmatejasiddabathina/maven-example.git'
   }
   
   stage('Compile-Package'){
	   //def mvnHome = tool name: 'MAVEN', type: 'maven'
          // bat "{mvnHome}/bin/mvn package"
	   mvn -f "C://Users//Dharmateja.S//.jenkins//workspace//Test_Maven_master//hello//pom.xml"
           bat 'mvn package'
   }
}
