//node{
//   stage('SCM Checkout'){
  //    git 'https://github.com/dharmatejasiddabathina/maven-example.git'
   //}
   
  // stage('Compile-Package'){
	   //def mvnHome = tool name: 'MAVEN', type: 'maven'
          // bat "{mvnHome}/bin/mvn package"
//	    bat 'mvn -f C://Users//Dharmateja.S//.jenkins//workspace//Test_Maven_master//hello//pom.xml package'
	   
           //bat 'mvn package'
  // }
//}

//pipeline{
	node{
	   stage('Scm Checkout')
		{
		 git 'https://github.com/dharmatejasiddabathina/maven-example.git'
		}
		stage('Compile & Build '){
		def evnMaven = tool name: 'MAVEN_HOME', type: 'maven'
			sh "${evnMaven}/bin/mvn package"
		}
	
	}
//}
