node{
   stage('SCM Checkout'){
      git 'https://github.com/dharmatejasiddabathina/maven-example.git'
   }
   
   stage('Compile-Package'){
	   //def mvnHome = tool name: 'MAVEN', type: 'maven'
           //bat "{mvnHome}/bin/mvn package"
   bat 'mvn package'
   }
}
